# Generated by Django 4.2.13 on 2024-08-05 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=200)),
                ('n_res_total', models.IntegerField()),
                ('res_ranges', models.CharField(max_length=200)),
                ('dom_pdbs', models.JSONField()),
                ('embeddings', models.JSONField()),
                ('targetdb', models.CharField(choices=[('afted', 'afted'), ('scope95', 'scope95'), ('scope40', 'scope40'), ('cath40', 'cath40'), ('ecod70', 'ecod70'), ('af21org', 'af21org')], default='afted', help_text='Choose a database to search against', max_length=20, verbose_name='Target database')),
                ('fileformat', models.CharField(choices=[('guess', 'guess'), ('pdb', 'pdb'), ('mmcif', 'mmcif'), ('mmtf', 'mmtf')], default='guess', max_length=20, verbose_name='File format')),
                ('minsimilarity', models.FloatField(default=0.8, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Minimum similarity')),
                ('maxhits', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Max number of hits')),
                ('chainsaw', models.BooleanField(default=False, verbose_name='Split domains')),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
