# Generated by Django 4.2.21 on 2026-01-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progres_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='targetdb',
            field=models.CharField(choices=[('afted', 'afted'), ('scope95', 'scope95'), ('scope40', 'scope40'), ('cath40', 'cath40'), ('ecod70', 'ecod70'), ('pdb100', 'pdb100'), ('bfvd', 'bfvd'), ('af21org', 'af21org')], default='afted', help_text="Choose a database to search against. afted is the <a href='https://www.science.org/doi/10.1126/science.adq4946'>TED domains</a> from the <a href='https://alphafold.ebi.ac.uk'>AlphaFold database</a>. bfvd is domains from the <a href='https://bfvd.foldseek.com'>Big Fantastic Virus Database (BFVD)</a>. scope95/scope40/cath40/ecod70 are domains from classifications of the PDB. pdb100 is the whole PDB split into domains with Chainsaw. af21org is domains from the AlphaFold set of 21 model organisms. See <a href='https://github.com/greener-group/progres#available-databases'>here</a> for more info.", max_length=20, verbose_name='Target database'),
        ),
    ]
